version: "3.8"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:rhamini
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress:ro
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:rhamini
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:rhamini
    # IMPORTANT : on ne charge plus env_file ici
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always

volumes:
  wordpress:
  mariadb:

networks:
  inception:
    driver: bridge